### PR TITLE
Password Manager

### PR DESCRIPTION
**Pull request by abanand132**
It is a  password manager which manages user password locally

### CODE REVIEW

**Review by Priyadarshan2000 — APPROVED** [review]
@abanand132 this is a fantastic Project! 
LGTM..Great Job 💯 @abanand132

**Comment by abanand132** [comment]
> @abanand132 this is a fantastic Project! LGTM..Great Job 💯 @abanand132

thank you bhaiya for your kind words

**Comment by CHIRANTAN-001** [comment]
@abanand132 great project buddy

**Comment by abanand132** [comment]
> @abanand132 great project buddy

thank you

**Pull request merged**
